services:
  - type: web
    name: python-trading-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir python_app app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
